### ISSUE TITLE
Does not work well with TSX files

### ISSUE THREAD

**Issue by chungweileong94** [biomejs/biome-zed#1] opened 2024-04-07 14:14 UTC
Not sure if this is a Zed language server bug, All the TSX files in the project don't seem to work properly. I ran `biome check .`, it's all good.

![image](https://github.com/biomejs/biome-zed/assets/15154097/cb762aef-a942-4332-a199-13d89a45284d)

**Comment by jackTabsCode** [comment] 2024-04-07 15:33
I'm getting these kinds of errors in TypeScript files too.

**Comment by luckydye** [comment] 2024-04-07 15:41
I have seen this too. 
Weird part is, it does work fine as a dev extension. Need to investigate...

**Comment by luckydye** [comment] 2024-04-07 18:09
I suspect its because the extension api for `language_ids` is not yet included with the stable release, which it seems the extensions are packaged with. It is included with zed v0.130.x, so waiting for v0.130 release is probably the solution here. 

This extension will need some time to mature, since extensions are so new to zed too.

**Comment by jackTabsCode** [comment] 2024-04-07 20:25
I tried the extension on the preview release and it is not working as intended and hallucinating about not being TypeScript

**Comment by chungweileong94** [comment] 2024-04-08 03:23
> Weird part is, it does work fine as a dev extension.

Yeah, I was able to get it to run properly as dev extension for some reason. Most probably a bug when Zed is trying to build the extension on production.

**Comment by chungweileong94** [comment] 2024-04-08 04:34
After some digging, it looks like the extension doesn't get packaged properly.
If you view the `~/Library/Application Support/Zed/extensions/installed/biome/extension.toml`, all the `language_ids` are not part of it, and manually add them in will fix the issue.

**Comment by luckydye** [comment] 2024-04-09 09:39
This will be fully fixed with [zed-0.131.x](https://github.com/biomejs/biome-zed/tree/zed-0.131.x).
Just waiting for at least pre-release.

**Closed** 2024-04-09 19:30 UTC
