### ISSUE TITLE
Biome making code actions freeze

### ISSUE THREAD

**Issue by christian-gama** [biomejs/biome-zed#14] opened 2024-05-03 13:58 UTC
I did not figure it out what is triggering this bug, but the code actions is simply not showing up after a random period of time after the IDE is open. Most of the times this bug happens within a minute or two after the IDE is open. The only way to make code actions work again is by restarting the IDE or disabling the Biome extension.

By freezing I mean that when I press cmd + . to trigger the code actions menu, nothing happens.

**Comment by chungweileong94** [comment] 2024-05-04 05:27
I’m not sure if this is Zed or Biome binary issue, but I managed to consistently reproduce the problem.

Basically I just perform “Go to Definition”, which will bring me to the node_modules source, if I continue to browse some files in there, and go back to my code again, all biome stuff stop working, linking, code action, formatted, etc.

I am thinking if this is because Zed/biome is having hard time to process too many files at a time.

**Comment by chungweileong94** [comment] 2024-05-04 05:38
One thing to note is that if you are using Biome 1.7.2, and perform the steps that I mentioned above, you will get this issue https://github.com/biomejs/biome/issues/2683, downgrade the version will get rid of the error, but the biome issue on Zed will remain. Which there might be a possibility where the 1.7.2 surface the issue.

**Comment by chungweileong94** [comment] 2024-05-04 07:21
After checking the LSP RPC logs, it seems like it's caused by Biome LSP, for some reason, Biome LSP stopped working properly after I started opening some files from `node_modules`. 

Setting the `vsc` option does help reduce this a lot,  but the problem will happen again randomly.
```json
"vcs": {
    "enabled": true,
    "clientKind": "git",
    "useIgnoreFile": true
}
```


https://github.com/biomejs/biome-zed/assets/15154097/7c224c58-0b36-4c53-a0a6-6a2ae61d76f5

**Comment by ematipico** [comment] 2024-05-06 15:53
Can you update to biome v1.7.3? We have an issue that was causing some panics

**Comment by chungweileong94** [comment] 2024-05-06 16:07
> Can you update to biome v1.7.3? We have an issue that was causing some panics

Yeah, just upgraded to 1.7.3, and the panics are no longer happening. Will have to give it a day or two to see if the LSP freeze issue still happening, but so far it looks pretty solid.

**Comment by thm76** [comment] 2024-05-07 04:42
I've got something similar, and it's still happening with 1.7.3
After a little while the biome extension seems to stop working - no formatting, no code actions, nothing. Restarting zed fixes it for a while.

I did notice this in the log just now:
2024-05-07T14:38:43+10:00 [ERROR] crates/lsp/src/lsp.rs:352: cannot read LSP message headers
2024-05-07T14:38:43+10:00 [WARN] Generic lsp request to biome_lsp failed: server shut down

Is there somewhere I can see more detailed logs?

**Comment by ematipico** [comment] 2024-05-07 06:05
I think this is a zed issue.

**Comment by luckydye** [comment] 2024-06-10 12:09
I have not seen this in a while btw. (Im on Zed 0.139 and biome 1.8.0)

**Comment by luckydye** [comment] 2024-06-30 18:34
I'll close this issue as it appears to be fixed.

https://github.com/zed-industries/zed/issues/10786

**Closed** 2024-06-30 18:34 UTC
