### ISSUE TITLE
Go to definition bug

### ISSUE THREAD

**Issue by Marcisbee** [biomejs/biome-zed#42] opened 2024-08-23 06:49 UTC
Just so you're aware. Biome extension seems to cause go-to-definition issues for other language servers.

Like `cmd+click` doesn't work at all if biome is enabled. When I disable biome, go-to-definition suddenly works. I'm not sure if this is some bug in zed or this extension. Just better to be aware of this.

Related issues:
- https://github.com/zed-industries/zed/issues/15917
- https://github.com/zed-industries/zed/issues/16619

**Comment by ematipico** [comment] 2024-08-23 06:55
Duplicate of https://github.com/biomejs/biome-zed/issues/40

**Closed by ematipico** 2024-08-23 06:55 UTC
